package com.example.presets

import com.example.audio.*

object PresetBank {
    val factoryPresets: List<SynthPatch> = listOf(
        SynthPatch(
            name = "Cyberpunk Bass",
            osc1Waveform = Waveform.SAWTOOTH,
            osc1Octave = -1,
            osc1Semi = 0,
            osc1Fine = 0f,
            osc1Volume = 0.9f,
            osc2Waveform = Waveform.SQUARE,
            osc2Octave = -2,
            osc2Semi = 0,
            osc2Fine = 0.04f,
            osc2Volume = 0.65f,
            filterType = FilterType.LOW_PASS,
            filterCutoff = 1200f,
            filterResonance = 4.0f,
            filterEnvAmount = 0.68f,
            ampAttack = 0.005f,
            ampDecay = 0.24f,
            ampSustain = 0.35f,
            ampRelease = 0.15f,
            filtAttack = 0.008f,
            filtDecay = 0.22f,
            filtSustain = 0.15f,
            filtRelease = 0.12f,
            lfoRate = 3.2f,
            lfoDepth = 0.2f,
            lfoShape = Waveform.TRIANGLE,
            delayTime = 0.22f,
            delayFeedback = 0.35f,
            delayMix = 0.18f,
            driveGain = 3.2f,
            glideTime = 0.035f,
            cables = listOf(
                PatchCable(source = PatchSource.AMP_ENV, destination = PatchDestination.FILTER_CUTOFF, amount = 0.55f, colorHex = 0xFF00E5FF)
            )
        ),
        SynthPatch(
            name = "Acid 303 Lead",
            osc1Waveform = Waveform.SQUARE,
            osc1Octave = 0,
            osc1Semi = 0,
            osc1Fine = 0f,
            osc1Volume = 0.9f,
            osc2Waveform = Waveform.SAWTOOTH,
            osc2Octave = 0,
            osc2Semi = 0,
            osc2Fine = 0.08f,
            osc2Volume = 0.35f,
            filterType = FilterType.LOW_PASS,
            filterCutoff = 900f,
            filterResonance = 7.5f,
            filterEnvAmount = 0.85f,
            ampAttack = 0.004f,
            ampDecay = 0.22f,
            ampSustain = 0.18f,
            ampRelease = 0.12f,
            filtAttack = 0.008f,
            filtDecay = 0.18f,
            filtSustain = 0.05f,
            filtRelease = 0.12f,
            lfoRate = 1.8f,
            lfoDepth = 0.25f,
            lfoShape = Waveform.TRIANGLE,
            delayTime = 0.32f,
            delayFeedback = 0.45f,
            delayMix = 0.28f,
            driveGain = 4.5f,
            glideTime = 0.07f,
            cables = listOf(
                PatchCable(source = PatchSource.FILTER_ENV, destination = PatchDestination.FILTER_RES, amount = 0.4f, colorHex = 0xFFFF9100)
            )
        ),
        SynthPatch(
            name = "Blade Runner Pad",
            osc1Waveform = Waveform.SAWTOOTH,
            osc1Octave = 0,
            osc1Semi = 0,
            osc1Fine = -0.04f,
            osc1Volume = 0.75f,
            osc2Waveform = Waveform.SAWTOOTH,
            osc2Octave = 0,
            osc2Semi = 7,
            osc2Fine = 0.06f,
            osc2Volume = 0.65f,
            filterType = FilterType.LOW_PASS,
            filterCutoff = 2800f,
            filterResonance = 2.2f,
            filterEnvAmount = 0.35f,
            ampAttack = 0.45f,
            ampDecay = 0.8f,
            ampSustain = 0.85f,
            ampRelease = 1.2f,
            filtAttack = 0.55f,
            filtDecay = 0.9f,
            filtSustain = 0.7f,
            filtRelease = 1.0f,
            lfoRate = 0.4f,
            lfoDepth = 0.45f,
            lfoShape = Waveform.SINE,
            delayTime = 0.48f,
            delayFeedback = 0.65f,
            delayMix = 0.45f,
            reverbSize = 0.85f,
            reverbDamp = 0.28f,
            reverbMix = 0.45f,
            driveGain = 1.4f,
            glideTime = 0.12f,
            cables = listOf(
                PatchCable(source = PatchSource.LFO_OUT, destination = PatchDestination.FILTER_CUTOFF, amount = 0.65f, colorHex = 0xFFFF4081)
            )
        ),
        SynthPatch(
            name = "Arcade 8-Bit Arp",
            osc1Waveform = Waveform.SQUARE,
            osc1Octave = 0,
            osc1Semi = 0,
            osc1Fine = 0f,
            osc1Volume = 0.85f,
            osc2Waveform = Waveform.NOISE,
            osc2Octave = 1,
            osc2Semi = 0,
            osc2Fine = 0f,
            osc2Volume = 0.15f,
            filterType = FilterType.BAND_PASS,
            filterCutoff = 3800f,
            filterResonance = 2.5f,
            filterEnvAmount = 0.2f,
            ampAttack = 0.002f,
            ampDecay = 0.14f,
            ampSustain = 0.45f,
            ampRelease = 0.06f,
            filtAttack = 0.002f,
            filtDecay = 0.12f,
            filtSustain = 0.3f,
            filtRelease = 0.05f,
            lfoRate = 8.0f,
            lfoDepth = 0.18f,
            lfoShape = Waveform.SQUARE,
            delayTime = 0.16f,
            delayFeedback = 0.25f,
            delayMix = 0.15f,
            driveGain = 1.8f,
            glideTime = 0.01f,
            cables = emptyList()
        ),
        SynthPatch(
            name = "Modular Chaos Drone",
            osc1Waveform = Waveform.TRIANGLE,
            osc1Octave = -1,
            osc1Semi = 0,
            osc1Fine = 0f,
            osc1Volume = 0.8f,
            osc2Waveform = Waveform.SINE,
            osc2Octave = 1,
            osc2Semi = 5,
            osc2Fine = 0.08f,
            osc2Volume = 0.6f,
            filterType = FilterType.LOW_PASS,
            filterCutoff = 1600f,
            filterResonance = 6.0f,
            filterEnvAmount = 0.45f,
            ampAttack = 0.6f,
            ampDecay = 1.2f,
            ampSustain = 0.9f,
            ampRelease = 1.5f,
            filtAttack = 0.8f,
            filtDecay = 1.0f,
            filtSustain = 0.7f,
            filtRelease = 1.2f,
            lfoRate = 0.22f,
            lfoDepth = 0.65f,
            lfoShape = Waveform.TRIANGLE,
            delayTime = 0.65f,
            delayFeedback = 0.72f,
            delayMix = 0.52f,
            reverbSize = 0.92f,
            reverbDamp = 0.35f,
            reverbMix = 0.55f,
            driveGain = 2.4f,
            glideTime = 0.15f,
            cables = listOf(
                PatchCable(source = PatchSource.LFO_OUT, destination = PatchDestination.FILTER_CUTOFF, amount = 0.75f, colorHex = 0xFF00E5FF),
                PatchCable(source = PatchSource.RANDOM_SH, destination = PatchDestination.OSC2_PITCH, amount = 0.5f, colorHex = 0xFF00E676)
            )
        ),
        SynthPatch(
            name = "Electric Dreams Keys",
            osc1Waveform = Waveform.SINE,
            osc1Octave = 0,
            osc1Semi = 0,
            osc1Fine = 0f,
            osc1Volume = 0.85f,
            osc2Waveform = Waveform.TRIANGLE,
            osc2Octave = 1,
            osc2Semi = 0,
            osc2Fine = 0.04f,
            osc2Volume = 0.5f,
            filterType = FilterType.LOW_PASS,
            filterCutoff = 3200f,
            filterResonance = 1.8f,
            filterEnvAmount = 0.4f,
            ampAttack = 0.01f,
            ampDecay = 0.6f,
            ampSustain = 0.35f,
            ampRelease = 0.45f,
            filtAttack = 0.015f,
            filtDecay = 0.45f,
            filtSustain = 0.25f,
            filtRelease = 0.35f,
            lfoRate = 4.5f,
            lfoDepth = 0.12f,
            lfoShape = Waveform.SINE,
            delayTime = 0.28f,
            delayFeedback = 0.4f,
            delayMix = 0.32f,
            reverbSize = 0.72f,
            reverbDamp = 0.4f,
            reverbMix = 0.35f,
            driveGain = 1.6f,
            glideTime = 0.02f,
            cables = emptyList()
        ),
        SynthPatch(
            name = "Analog Moog Brass",
            osc1Waveform = Waveform.SAWTOOTH,
            osc1Octave = 0,
            osc1Semi = 0,
            osc1Fine = -0.05f,
            osc1Volume = 0.85f,
            osc2Waveform = Waveform.SAWTOOTH,
            osc2Octave = 0,
            osc2Semi = 0,
            osc2Fine = 0.06f,
            osc2Volume = 0.8f,
            filterType = FilterType.LOW_PASS,
            filterCutoff = 2200f,
            filterResonance = 3.8f,
            filterEnvAmount = 0.75f,
            ampAttack = 0.06f,
            ampDecay = 0.35f,
            ampSustain = 0.7f,
            ampRelease = 0.28f,
            filtAttack = 0.05f,
            filtDecay = 0.3f,
            filtSustain = 0.4f,
            filtRelease = 0.25f,
            lfoRate = 5.0f,
            lfoDepth = 0.15f,
            lfoShape = Waveform.SINE,
            delayTime = 0.2f,
            delayFeedback = 0.3f,
            delayMix = 0.2f,
            driveGain = 2.8f,
            glideTime = 0.04f,
            cables = listOf(
                PatchCable(source = PatchSource.AMP_ENV, destination = PatchDestination.FILTER_CUTOFF, amount = 0.6f, colorHex = 0xFF00E5FF)
            )
        ),
        SynthPatch(
            name = "Sub Bass Heavy",
            osc1Waveform = Waveform.SINE,
            osc1Octave = -2,
            osc1Semi = 0,
            osc1Fine = 0f,
            osc1Volume = 0.95f,
            osc2Waveform = Waveform.TRIANGLE,
            osc2Octave = -1,
            osc2Semi = 0,
            osc2Fine = 0.02f,
            osc2Volume = 0.5f,
            filterType = FilterType.LOW_PASS,
            filterCutoff = 650f,
            filterResonance = 1.5f,
            filterEnvAmount = 0.4f,
            ampAttack = 0.008f,
            ampDecay = 0.28f,
            ampSustain = 0.6f,
            ampRelease = 0.2f,
            filtAttack = 0.01f,
            filtDecay = 0.22f,
            filtSustain = 0.2f,
            filtRelease = 0.18f,
            lfoRate = 1.0f,
            lfoDepth = 0.1f,
            lfoShape = Waveform.SINE,
            delayTime = 0.15f,
            delayFeedback = 0.1f,
            delayMix = 0.05f,
            driveGain = 3.6f,
            glideTime = 0.05f,
            cables = emptyList()
        ),
        SynthPatch(
            name = "Stranger Synth 80s",
            osc1Waveform = Waveform.SAWTOOTH,
            osc1Octave = 0,
            osc1Semi = 0,
            osc1Fine = -0.06f,
            osc1Volume = 0.85f,
            osc2Waveform = Waveform.SQUARE,
            osc2Octave = -1,
            osc2Semi = 0,
            osc2Fine = 0.06f,
            osc2Volume = 0.75f,
            filterType = FilterType.LOW_PASS,
            filterCutoff = 2200f,
            filterResonance = 4.2f,
            filterEnvAmount = 0.65f,
            ampAttack = 0.005f,
            ampDecay = 0.25f,
            ampSustain = 0.5f,
            ampRelease = 0.22f,
            filtAttack = 0.008f,
            filtDecay = 0.22f,
            filtSustain = 0.3f,
            filtRelease = 0.2f,
            lfoRate = 4.2f,
            lfoDepth = 0.18f,
            lfoShape = Waveform.TRIANGLE,
            delayTime = 0.35f,
            delayFeedback = 0.52f,
            delayMix = 0.38f,
            chorusRate = 1.4f,
            chorusDepth = 0.6f,
            chorusMix = 0.55f,
            reverbSize = 0.78f,
            reverbDamp = 0.3f,
            reverbMix = 0.38f,
            driveGain = 2.4f,
            glideTime = 0.03f,
            cables = listOf(
                PatchCable(source = PatchSource.AMP_ENV, destination = PatchDestination.FILTER_CUTOFF, amount = 0.45f, colorHex = 0xFFFF0055)
            )
        ),
        SynthPatch(
            name = "Vangelis CS-80 Pad",
            osc1Waveform = Waveform.SAWTOOTH,
            osc1Octave = 0,
            osc1Semi = 0,
            osc1Fine = -0.08f,
            osc1Volume = 0.8f,
            osc2Waveform = Waveform.SAWTOOTH,
            osc2Octave = 0,
            osc2Semi = 7,
            osc2Fine = 0.08f,
            osc2Volume = 0.75f,
            filterType = FilterType.LOW_PASS,
            filterCutoff = 3400f,
            filterResonance = 2.8f,
            filterEnvAmount = 0.4f,
            ampAttack = 0.55f,
            ampDecay = 0.9f,
            ampSustain = 0.85f,
            ampRelease = 1.4f,
            filtAttack = 0.65f,
            filtDecay = 1.1f,
            filtSustain = 0.7f,
            filtRelease = 1.2f,
            lfoRate = 0.5f,
            lfoDepth = 0.35f,
            lfoShape = Waveform.SINE,
            delayTime = 0.55f,
            delayFeedback = 0.68f,
            delayMix = 0.48f,
            chorusRate = 0.8f,
            chorusDepth = 0.75f,
            chorusMix = 0.68f,
            reverbSize = 0.94f,
            reverbDamp = 0.22f,
            reverbMix = 0.58f,
            driveGain = 1.5f,
            glideTime = 0.15f,
            cables = listOf(
                PatchCable(source = PatchSource.LFO_OUT, destination = PatchDestination.FILTER_CUTOFF, amount = 0.5f, colorHex = 0xFF00E5FF)
            )
        )
    )
}
